language: python

python:
  - "3.6.9"

install:
  - make deps

script:
  - make lint
  - make test
  - make test_cov

after_success:
  - make docker_push

deploy:
  provider: heroku
  app: flask-nip-regon-pesel
  api_key: ${HEROKU_API_KEY}